baseURL = "https://y-stdout.netlify.com/"
languageCode = "ja-JP"
title = "y.stdout"
theme = "hugo_theme_robust"
# 記事の要約を短くする
hasCJKLanguage = true

googleAnalytics = "UA-112771505-1" # Optional
# disqusShortname = "XYW"

[permalinks]
  post = "/:year/:month/:day/:slug"

[taxonomies]
  tag = "tags"

[outputs]
  home = [ "HTML", "RSS" ]
  page = [ "HTML", "AMP" ]

################
# Robust Setting
################
[params]
  description = "気の向くままに更新するブログです"
  # dateformat = "Jan 2, 2006" # Optional

  # Fonts settings.
  # googlefonts = "https://fonts.googleapis.com/css?family=Lobster|Lato:400,700" # Optional, Include google fonts.
  # fontfamily = "Lato,YuGothic,'Hiragino Kaku Gothic Pro',Meiryo,sans-serif" # Optional, Override body font family.
  # logofontfamily = "Lobster, cursive" # Optional, Override logo font.

[params.author]
  thumbnail = "images/author.jpg"
  name = "yusuket"
  description = "なんちゃって技術者です<br>このブログについては<a href=https://y-stdout.netlify.com/2018/01/22/ブログ始めました/>こちら</a>"
  # facebook = "https://www.facebook.com/xxxxxx"
  rss = "https://y-stdout.netlify.com/index.xml"
  twitter = "https://twitter.com/bridgement"
  # qiita = "https://qiita.com/yusuket"
  # github = "https://github.com/xxxxxx"

