baseURL = "https://blog.bridgey.dev/"
languageCode = "ja-JP"
title = "blog.bridgey.dev"
theme = "tale"
# 記事の要約を短くする
hasCJKLanguage = true

# 絵文字の有効化
enableEmoji = true

# googleAnalytics = "" # Optional
# disqusShortname = "XYW"

# syntax highlight
pygmentsUseClasses = true
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
# pygmentsStyle = "manni"

[permalinks]
  post = "/:year/:month/:day/:slug"

[taxonomies]
  tag = "tags"

[outputs]
  home = [ "HTML", "RSS" ]
  page = [ "HTML", "AMP" ]

[Params]
  css = ["/css/toc.css", "/css/blockquote.css", "/css/syntax.css", "/css/table.css"]
  mainSections = ["post"]

[Author]
  name = "yusuke"

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 3

[[menu.main]]
  name = "Tags"
  url = "/tags"
  weight = 2

